site_name: My Docs
nav:
  - Home: index.md
  - Computers:
    - 'Linux How-Tos': ./computers/LinuxHowTos.md
    - 'Proxmox': ./computers/Proxmox.md
    - 'Home Proxmox Server': ./computers/HomeProxmoxServer.md
    - 'AI': ./computers/AI/AI.md
  - '3d Printing':
    - Klipper: ./3dPrinting/Klipper.md
    - 'Orca slicer': ./3dPrinting/OrcaSlicer.md
  - MKDocs: MKDocsHowTos.md
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
plugins:
  - search

markdown_extensions:
  - attr_list
 

    